Setup frontend with react
tonnytech/hello-react-front-end pull request #1
Opened 2023-10-25 07:08 UTC by tonnytech

Did the following in this pull request:

- Create a new React app called 'hello-react-front-end'
- Initialize your project with Git.
- Create the App component with react-router.
- Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
- Display the random greeting in your Greeting component.

2023-10-25 07:57 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @tonnytech, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Implemented some project requirements. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 07:57 UTC, Qoosim commented on src/redux/greetingSlice.js
> +    return greeting;
- [ ] Great job so far. However, there's one small thing you need to work on. Your frontend app is facing resource from different origin issue. That's open your app from a new browser different from the one on which the app was built. Kindly look into this [article](https://www.stackhawk.com/blog/react-cors-guide-what-it-is-and-how-to-enable-it/) to get some insight about `cors policy`.

### Page Display

![cors-error](https://github.com/tonnytech/hello-react-front-end/assets/26597432/8cdb9c52-62a9-4066-97a2-8ad6ed9886f0)

2023-10-25 10:52 UTC, Gambit142 requested changes
Hi @tonnytech 👋, 

Great work on making the changes requested by a previous reviewer 👏 

### Highlights
- Setup linters correctly ✔️ 
- Setup redux store properly ✔️ 
- Setup `Greeting` component ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments in the backend repository pull request._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-28 11:43 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @tonnytech**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- There is an `App` component with routes that leads to the `Greeting` component. ✔️ 
- There is a `Greeting` component.. ✔️ 
There is a store, an action, and a reducer that uses the url to the endpoint from the Rails API. 👍🏻 
- The two apps work together; keep rocking :rocket: 

![image](https://github.com/AJ193/hello-react-front-end/assets/79058364/af1dae83-fd70-4237-8c13-85008260a232)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-09-05 05:57 UTC, merged